#!/bin/sh
set -eu

out="${1:?}"
repo_root="${2:?}"

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

if command -v git >/dev/null 2>&1 && [ -d "$repo_root/.git" ]; then
    head_branch="$(git -C "$repo_root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
    base_ref=""
    if git -C "$repo_root" show-ref --quiet refs/remotes/origin/master; then
        base_ref="origin/master"
    fi

    branches_list="$(git -C "$repo_root" for-each-ref --format='%(refname:short)' refs/heads)"
    had_branch=0
    {
        for branch in $branches_list; do
            if git -C "$repo_root" merge-base --is-ancestor "$branch" HEAD 2>/dev/null; then
                if [ -n "$base_ref" ]; then
                    log="$(git -C "$repo_root" log --pretty=format:'%h - %s' --no-color "${base_ref}..${branch}")"
                else
                    log="$(git -C "$repo_root" log --pretty=format:'%h - %s' --no-color "${branch}")"
                fi
                if [ -n "$log" ]; then
                    printf "+ %s\n" "$branch"
                    printf "%s\n" "$log" | sed 's/^/   * /'
                    had_branch=1
                fi
            fi
        done

        if [ "$had_branch" -eq 0 ]; then
            printf "+ %s\n" "$head_branch"
            if [ -n "$base_ref" ]; then
                log="$(git -C "$repo_root" log --pretty=format:'%h - %s' --no-color "${base_ref}..HEAD")"
                if [ -n "$log" ]; then
                    printf "%s\n" "$log" | sed 's/^/   * /'
                else
                    printf "   * (no local commits)\n"
                fi
            else
                git -C "$repo_root" log --pretty=format:'%h - %s' --no-color HEAD | sed 's/^/   * /'
            fi
        fi

        if [ -n "$base_ref" ]; then
            base_hash="$(git -C "$repo_root" rev-parse --short "$base_ref" 2>/dev/null || true)"
            if [ -n "$base_hash" ]; then
                printf "+ base %s (%s)\n" "$base_ref" "$base_hash"
            fi
        fi
    } > "$tmp_file"
else
    printf "+ manifest\n   * (git metadata unavailable)\n" > "$tmp_file"
fi

{
    printf "/* Auto-generated by mk/gen_manifest.sh; do not edit. */\n"
    printf "#include \"manifest.h\"\n\n"
    printf "const char *manifest_get(void)\n{\n"
    printf "    return\n"
    while IFS= read -r line; do
        esc=$(printf '%s' "$line" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
        printf '        "%s\\n"\n' "$esc"
    done < "$tmp_file"
    printf "        \"\";\n"
    printf "}\n"
} > "$out"
