#!/bin/sh
set -eu

out="${1:?}"
repo_root="${2:?}"

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

if command -v git >/dev/null 2>&1 && [ -d "$repo_root/.git" ]; then
    base_ref="3d28f6b1"
    if ! git -C "$repo_root" rev-parse --verify "$base_ref" >/dev/null 2>&1; then
        base_ref=""
    fi

    if git -C "$repo_root" rev-parse --verify origin/master >/dev/null 2>&1; then
        have_origin=1
    else
        have_origin=0
    fi

    {
        printf "Commits in this build:\n"
        if [ -n "$base_ref" ]; then
            log="$(git -C "$repo_root" log --pretty=format:'%h%x09%s' --no-color "${base_ref}..HEAD")"
        else
            log="$(git -C "$repo_root" log --pretty=format:'%h%x09%s' --no-color HEAD)"
        fi
        if [ -n "$log" ]; then
            printf "%s\n" "$log" | while IFS="$(printf '\t')" read -r hash subject; do
                if [ "$have_origin" -eq 1 ] && ! git -C "$repo_root" merge-base --is-ancestor "$hash" origin/master 2>/dev/null; then
                    printf "   * <color:o>%s - %s</color>\n" "$hash" "$subject"
                else
                    printf "   * %s - %s\n" "$hash" "$subject"
                fi
            done
        else
            printf "   * (no local commits)\n"
        fi

        if [ "$have_origin" -eq 1 ]; then
            printf "\nAdditional origin commits available:\n"
            if [ -n "$base_ref" ]; then
                log="$(git -C "$repo_root" log --pretty=format:'%h%x09%s' --no-color "${base_ref}..origin/master" ^HEAD)"
            else
                log="$(git -C "$repo_root" log --pretty=format:'%h%x09%s' --no-color origin/master ^HEAD)"
            fi
            if [ -n "$log" ]; then
                printf "%s\n" "$log" | while IFS="$(printf '\t')" read -r hash subject; do
                    printf "   * <color:y>%s - %s</color>\n" "$hash" "$subject"
                done
            else
                printf "   * (none)\n"
            fi
        fi
    } > "$tmp_file"
else
    printf "+ manifest\n   * (git metadata unavailable)\n" > "$tmp_file"
fi

{
    printf "/* Auto-generated by mk/gen_manifest.sh; do not edit. */\n"
    printf "#include \"manifest.h\"\n\n"
    printf "const char *manifest_get(void)\n{\n"
    printf "    return\n"
    while IFS= read -r line; do
        esc=$(printf '%s' "$line" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
        printf '        "%s\\n"\n' "$esc"
    done < "$tmp_file"
    printf "        \"\";\n"
    printf "}\n"
} > "$out"
